                                         Numpy Array vs Python List

Benefit #1 : Less Memory

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
l = [1,2,3]
l

[1, 2, 3]

In [6]:
python_list = list(range(100))
python_list[:9]

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [8]:
numpy_array = np.arange(100)
numpy_array[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
import sys

sys.getsizeof(python_list[0])*len(python_list)

2800

In [10]:
numpy_array.nbytes

800

In [12]:
l1 = [1,2,3]
l2 = [8,7,9]
tuple(zip(l1,l2))

((1, 8), (2, 7), (3, 9))

In [15]:
l1 = [1,2,3]
l2 = [8,7,9]
for x,y in zip(l1,l2):
    print (x,y)

1 8
2 7
3 9


Benefit #2 : Speed

In [16]:
import time

SIZE = 1000000

l1 = list(range(SIZE))
l2 = list(range(SIZE))

start_time = time.time()
l3 = [x+y for x,y in zip(l1,l2)]
end_time = time.time()

print("Python list took: ", end_time - start_time)

Python list took:  0.055054426193237305


In [17]:
n1 = np.arange(SIZE)
n2 = np.arange(SIZE)
n1[:4], n2[:4]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [18]:
start_time = time.time()
n3 = n1 + n2
end_time = time.time()
print("NUmpy array took: ", end_time-start_time)

NUmpy array took:  0.009096622467041016


Benefit #3 : Convenient use with built in functions

In [19]:
l1 = list(range(5))
l2 = list(range(5))
l1[:3], l2[:3]

([0, 1, 2], [0, 1, 2])

In [20]:
l3 = [ x + y for x,y in zip (l1,l2)]
l3

[0, 2, 4, 6, 8]

In [21]:
n1 = np.arange(5)
n2 = np.arange(5)
n1, n2

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [22]:
n1 -n2

array([0, 0, 0, 0, 0])

In [23]:
n1 * n2

array([ 0,  1,  4,  9, 16])