In [1]:
import numpy as np

In [2]:
rev_q1 = np.array([10,12,9])
rev_q1.ndim

1

In [26]:
rev = np.array([[10,12,9],[15,11,13]])
rev.ndim

2

In [27]:
rev

array([[10, 12,  9],
       [15, 11, 13]])

In [28]:
rev[1,0]

np.int64(15)

In [29]:
rev[1,0]=14
rev

array([[10, 12,  9],
       [14, 11, 13]])

In [30]:
rev.dtype

dtype('int64')

In [31]:
rev.nbytes

48

In [33]:
rev.itemsize

8

In [51]:
revf = np.array([[10, 12,  9],[14, 11, 13]], dtype = np.float32)
revf.dtype

dtype('float32')

In [35]:
revf.nbytes

24

In [ ]:
revf.itemsize

4

In [36]:
revf.size

6

In [37]:
rev.shape

(2, 3)

In [38]:
np.sort(revf)

array([[ 9., 10., 12.],
       [11., 13., 14.]], dtype=float32)

In [39]:
np.sort(revf, axis =None)

array([ 9., 10., 11., 12., 13., 14.], dtype=float32)

In [40]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.arange(4)

array([0, 1, 2, 3])

In [46]:
np.arange(20,30)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [47]:
np.arange(20,30,3)

array([20, 23, 26, 29])

In [48]:
np.linspace(10,20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [49]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [52]:
revf

array([[10., 12.,  9.],
       [14., 11., 13.]], dtype=float32)

In [ ]:
revf.ravel()
#it create only a view, it may not modify the original array

array([10., 12.,  9., 14., 11., 13.], dtype=float32)

In [ ]:
revf.flatten()
# it results a new array which can be modified

array([10., 12.,  9., 14., 11., 13.], dtype=float32)

In [62]:
revf.reshape(3,2)


array([[10., 12.],
       [ 9., 14.],
       [11., 13.]], dtype=float32)

In [61]:
revf.reshape(6,1)

array([[10.],
       [12.],
       [ 9.],
       [14.],
       [11.],
       [13.]], dtype=float32)

In [63]:
revf.min()

np.float32(9.0)

In [64]:
revf.max()

np.float32(14.0)

In [ ]:
revf.sum(axis=1)
#adding horizontally

array([31., 38.], dtype=float32)

In [ ]:
revf.sum(axis=0)
#adding vertically

array([24., 23., 22.], dtype=float32)

In [68]:
rev

array([[10, 12,  9],
       [14, 11, 13]])

In [69]:
for row in rev:
    print("row:-> ", row)

row:->  [10 12  9]
row:->  [14 11 13]


In [72]:
for a in rev:
    print("b-> ", a)

b->  [10 12  9]
b->  [14 11 13]


In [73]:
b = np.array([1,4,16,18])

In [74]:
np.sqrt(b)

array([1.        , 2.        , 4.        , 4.24264069])

In [75]:
np.square(b)

array([  1,  16, 256, 324])

In [76]:
np.std(b)
# standard deviation

np.float64(7.361215932167728)