In [6]:
import numpy as np

In [7]:
a = np.array([6,7,8,9])

In [8]:
a[0:3]
# 0 is included , 3 is not included

array([6, 7, 8])

In [9]:
a[2:]

array([8, 9])

In [10]:
a[-1:]

array([9])

In [11]:
a[-3:]

array([7, 8, 9])

In [12]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [13]:
b[1,2]

np.int64(6)

In [14]:
b[2,0]

np.int64(7)

In [15]:
b[-1,]

array([7, 8, 9])

In [16]:
b[-1, 0:2]

array([7, 8])

In [17]:
b[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [18]:
# customer ID, Name
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])

# Customer Id, Purchase amount, Purchase date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

In [19]:
np.hstack((c,d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [20]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

In [21]:
e = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy']
])
e

array([['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [22]:
np.vstack((c,e))

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [23]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
     [103, 'Fatima', 300.75 , '2023-08-02'] ,
 [104, 'David', 400.20, '2023-08-03'] ,  
     [105, 'Aryan', 330.1, '2023-08-04'],
])

a, b = np.hsplit(transactions, [3])

In [24]:
a

array([['101', 'Mohan', '250.5'],
       ['102', 'Bob', '150.0'],
       ['103', 'Fatima', '300.75'],
       ['104', 'David', '400.2'],
       ['105', 'Aryan', '330.1']], dtype='<U32')

In [25]:
b

array([['2023-08-01'],
       ['2023-08-02'],
       ['2023-08-02'],
       ['2023-08-03'],
       ['2023-08-04']], dtype='<U32')

In [44]:
x,y = np.vsplit(transactions, [2])

In [45]:
x

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')

In [28]:
y

array([['103', 'Fatima', '300.75', '2023-08-02'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [29]:
monthly_sales = np.array([30, 33, 35, 28, 42])

result = monthly_sales < 32 
result

array([ True, False, False,  True, False])

In [30]:
monthly_sales[result]

array([30, 28])

In [31]:
monthly_sales.max()

np.int64(42)

In [32]:
index = np.argmax(monthly_sales)
index

np.int64(4)

In [33]:
transactions[index]

array(['105', 'Aryan', '330.1', '2023-08-04'], dtype='<U32')

In [34]:
transactions[:, 2].astype(float)

array([250.5 , 150.  , 300.75, 400.2 , 330.1 ])

In [35]:
t_index = np.argmax(transactions[:, 2].astype(float))
t_index

np.int64(3)

In [36]:
transactions[t_index]

array(['104', 'David', '400.2', '2023-08-03'], dtype='<U32')

In [37]:
transactions[:,0]

array(['101', '102', '103', '104', '105'], dtype='<U32')

In [38]:
transactions[transactions[:,0]=='102']

array([['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')